---
- name: Confirm basic ansible connectivity
  ping:

- name: Confirm connectivity with all hosts
  run_once: true
  assert:
    that:
    - ansible_play_hosts == ansible_play_hosts_all

- name: Wait for cloud-init to complete
  stat:
    path: /var/lib/cloud/instance/boot-finished
  ignore_unreachable: true
  register: boot_finished
  until: boot_finished.stat.exists
  retries: 6
  delay: 10

- name: Validate basic ansible connectivity after cloud-init
  ping:
  ignore_unreachable: true
  retries: 6
  delay: 10

- name: Validate that cloud-init completed
  stat:
    path: /var/lib/cloud/instance/boot-finished
  register: boot_finished
  until: boot_finished.stat.exists
  retries: 1
  delay: 10

- name: Validate connectivity with all hosts remains
  run_once: true
  assert:
    that:
    - ansible_play_hosts == ansible_play_hosts_all
