---
- name: Update all packages
  become: true
  dnf:
    name: '*'
    state: latest

- name: Check if reboot is needed
  become: true
  command: dnf needs-rebooting -r
  failed_when: false
  changed_when: false
  register: needs_rebooting

- name: Reboot {{ ansible_host }}
  become: true
  reboot:
  when: needs_rebooting.rc != 0
