---
- name: Update all packages
  become: true
  dnf:
    name: '*'
    state: latest
  when: '{{ hostvars.controller.terraform.changed }}'

- name: Check if reboot is needed
  become: true
  command: dnf needs-restarting -r
  failed_when: false
  changed_when: false
  register: needs_rebooting

- name: Reboot if necessary
  become: true
  reboot:
  when: needs_rebooting.rc != 0
