---
name: Check

on:
  pull_request:

jobs:

  tflint:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      name: Checkout code

    - uses: hashicorp/setup-terraform@v1
      name: Setup Terraform

    - name: Init terraform
      run: terraform init

    - uses: reviewdog/action-tflint@master
      name: Run tflint
      with:
        github_token: ${{ secrets.REVIEWDOG_GITHUB_TOKEN }}
        fail_on_error: true
      env:
        TFLINT_PLUGIN_DIR: ./tflint.d/plugins

  tfsec:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      name: Checkout code

    - uses: reviewdog/action-tfsec@master
      name: Run tfsec
      with:
        github_token: ${{ secrets.REVIEWDOG_GITHUB_TOKEN }}
        fail_on_error: true

  fmt:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      name: Checkout code

    - uses: hashicorp/setup-terraform@v1
      name: Setup Terraform

    - name: Check format
      run: terraform fmt -check
